# Site settings
title: Hugo
description: "Cybersecurity researcher with emphasis on program analysis, smartphone security and reverse engineering."
url: 'http://www.fengguow.dev'
google-tracking-id: 'UA-86179253-1'

author:
  name: 'Fengguo (Hugo) Wei'
  email: fwei@mail.usf.edu
  github_username:  fgwei
  linkedin_username:  fgwei

################
# Header layout #
################

black-favicon: "images/black-lab-glass.ico"

background-img: "../images/cover.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Dream as if you'll live forever."
  - text: "Live as if you'll die today."

# sections
sections:
  - id: 'about'
    name: 'About'
    tpl: 'about.md'
    css: ''
  - id: 'opensource'
    name: 'Open-Source'
    tpl: 'opensource.html'
    css: ''
  - id: 'project'
    name: 'Project'
    tpl: 'project.html'
    css: 'testimonials navy-section'
  - id: 'skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: ''
  - id: 'timeline'
    name: 'Timeline'
    tpl: 'timeline.html'
    css: 'mytime'

############
# 404 page #
############

404-img: "/images/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: fgwei
keybase-in-social: True
keybase-in-footer: True

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
